Library/Models/Book.cs
using Library.Interfaces;
using Library.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace Library.Models
{
    public class Book
    {
        //public Book()
        //{
        //    this.Users = new HashSet<User>();
        //}
        public int ID { get; set; }
        [Required]
        [MaxLength(14),MinLength(14)]
        [RegularExpression("[0-9]*", ErrorMessage = "Invalid ISBN ")]
        public string Title { get; set; }
        [Required]
        [RegularExpression("[0-9]*", ErrorMessage = "Invalid ISBN ")]
        public int ISBN { get; set; }
        [Required]
        [RegularExpression("[1-9][0-9]*", ErrorMessage = "Invalid Yeare ")]
        public int Yeare { get; set; }
        [Required]
        [Display(Name ="Author Name")]
        public string AuthorName { get; set; }

        [Display(Name = "PImage")]
        public Image PImage { get; set; }

        [Display(Name = "File")]
        public string FilePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase File { get; set; }
        public string ImagePath { get; set; }
        
        [NotMapped]
        public HttpPostedFileBase Image { get; set; }
        [ForeignKey("User")]
        public Nullable<int> UserID { get; set; }
        public virtual UserA User { get; set; }
        [ForeignKey("Department")]
        public int DepartmentID { get; set; }
        public virtual Department Department { get; set; }
        [ForeignKey("Publisher")]
        public int PublisherID { get; set; }
        public virtual Publisher Publisher { get; set; }

        public virtual ICollection<Author> Authors { get; set; }
    }
}

Library/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Library.ViewModels;
using System.Data.Entity.Validation;
using System.Diagnostics;
using Library.Models;
using Library.Interfaces;

namespace Library.Controllers
{
    public static class  photo{
        /// <summary>
        /// Upoade photo To server
        /// Constrain: 
        ///         object Contain Image Must have proparty
        ///             1- PhotoPath  as String
        ///             2- Photo as HttpPostedFileBase
        /// </summary>
        /// <param name="ObjectConatinImage"></param>
        /// <param name="image"></param>
        public static HttpStatusCode UploadPhoto(dynamic ObjectConatinImage, HttpPostedFileBase image)
        {
            try
            {
                
                    if (image != null)
                    {
                        string fileName = Path.GetFileName(image.FileName);
                        string ServerPath = HttpContext.Current.Server.MapPath("~/Image/");
                        string imgPath = Path.Combine(ServerPath, fileName);
                        ObjectConatinImage.ImagePath = "~/Image/" + fileName;
                        ObjectConatinImage.Image.SaveAs(imgPath);
                        return HttpStatusCode.OK;
                    }
                    else
                    {
                        return HttpStatusCode.BadRequest;
                    }
                return HttpStatusCode.BadRequest;
            }
            catch (Exception e)
            {
                return HttpStatusCode.InternalServerError;
            }
        }

        /// <summary>
        /// Upoade photo To server
        /// Constrain: 
        ///         object Contain Image Must have proparty
        ///             1- PhotoPath  as String
        ///             2- Photo as HttpPostedFileBase
        /// </summary>
        /// <param name="ObjectConatinFile"></param>
        /// <param name="File"></param>
        public static HttpStatusCode UploadFile(dynamic ObjectConatinFile, HttpPostedFileBase File)
        {
            try
            {

                if (File != null)
                {
                    string fileName = Path.GetFileName(File.FileName);
                    string ServerPath = HttpContext.Current.Server.MapPath("/Content/File/");
                    string filePath = Path.Combine(ServerPath, fileName);
                    ObjectConatinFile.FilePath = "/Content/File/" + fileName;
                    ObjectConatinFile.File.SaveAs(filePath);
                    return HttpStatusCode.OK;
                }
                else
                {
                    return HttpStatusCode.BadRequest;
                }
                return HttpStatusCode.BadRequest;
            }
            catch (Exception e)
            {
                return HttpStatusCode.InternalServerError;
            }
        }

    }
    public class BooksController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();

        //[Authorize]
        public ActionResult AllBook()
        {
            TempData.Keep("userName");

            var books = context.Books.Include(b => b.Department).Include(b => b.Publisher).Include(b => b.User);
            return View(books.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = context.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            TempData.Keep("userName");

            return View(book);
        }

        public ActionResult AddNewBook()
        {
            //ViewData["dept"] = context.Departments.ToList();
            //ViewData["pub"] = context.Publishers.ToList();
            ViewData["usr"] = context.Users.ToList();
            TempData.Keep("userName");
            ViewModel ViewModelM = new ViewModel();
            List<Publisher> publishers = context.Publishers.ToList();
            List<Department> departments  = context.Departments.ToList();

            IEnumerable<SelectListItem> selPublisher = from c in publishers
                                                       select new SelectListItem
                                                       {
                                                           Text = c.Name,
                                                           Value = c.ID.ToString()
                                                       };
            IEnumerable<SelectListItem> selDepartment = from c in departments
                                                       select new SelectListItem
                                                       {
                                                           Text = c.Name,
                                                           Value = c.ID.ToString()
                                                       };
            ViewModelM.Publishers = selPublisher;
            ViewModelM.Departments = selDepartment;
            /*
            ViewBag.DeptID = new SelectList(context.Departments, "ID", "Name");
            ViewBag.PublID = new SelectList(context.Publishers, "ID", "Name");
            ViewBag.UserID = new SelectList(context.Users, "ID", "Name");
            */
            return View(ViewModelM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public ActionResult AddNewBook(Book book)
        {
            Book BookDB = context.Books.FirstOrDefault(b => b.ID == book.ID);
            

            ViewModel ViewModelM = new ViewModel();
            List<Publisher> publishers = context.Publishers.ToList();
            List<Department> departments = context.Departments.ToList();

            IEnumerable<SelectListItem> selPublisher = from c in publishers
                                                       select new SelectListItem
                                                        {
                                                            Text = c.Name,
                                                            Value = c.ID.ToString()
                                                        };
            IEnumerable<SelectListItem> selDepartment = from c in departments
                                                        select new SelectListItem
                                                        {
                                                            Text = c.Name,
                                                            Value = c.ID.ToString()
                                                        };
            ViewModelM.Publishers = selPublisher;
            ViewModelM.Departments = selDepartment;
            if (ModelState.IsValid)
            {

                //check whether name is already exists in the database or not
                bool nameAlreadyExists = context.Books.Any(b => b.Title == book.Title);


                if (nameAlreadyExists)
                {
                    //adding error message to ModelState
                    ModelState.AddModelError("Title", "Book Name Already Exists.");
//                    ViewData["dept"] = context.Departments.ToList();
                    ViewData["usr"] = context.Users.ToList();
                    //                    ViewData["pub"] = context.Publishers.ToList();

                    ViewModelM.Book = book;
                    ViewModelM.Publishers = selPublisher;
                    ViewModelM.Departments = selDepartment;
                    return View(ViewModelM);
                }
                //if (book.Image != null && book.Image.ContentLength > 0)
                //{
                //    string fileName = Path.GetFileName(book.Image.FileName);
                //    string imgPath = Path.Combine(Server.MapPath("~/Image/"), fileName);
                //    book.ImagePath = "~/Image/" + fileName;
                //    book.Image.SaveAs(imgPath);

                //}
                photo.UploadPhoto(book, book.Image);
                photo.UploadFile(book, book.File);
                context.Books.Add(book);
                context.SaveChanges();
                Author author = new Author();
                author.Name = book.AuthorName;
                author.BookID = book.ID;
                author.Book = book;
                context.Authors.Add(author);
                context.SaveChanges();
                Book BoDB = context.Books.FirstOrDefault(b => b.ID == book.ID);
                BoDB.Authors.Add(context.Authors.FirstOrDefault(b => b.ID == author.ID));
                context.SaveChanges();
                ViewModelM.Book = book;
                return RedirectToAction("AllBook");
            }
            //ViewData["dept"] = context.Departments.ToList();
            ViewData["usr"] = context.Users.ToList();
            //ViewData["pub"] = context.Publishers.ToList();
            TempData.Keep("userName");

            //ViewBag.DeptID = new SelectList(context.Departments, "ID", "Name", book.Department.ID);
            //ViewBag.PublID = new SelectList(context.Publishers, "ID", "Name", book.Publisher.ID);
            return View(ViewModelM);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = context.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewData["dept"] = context.Departments.ToList();
            ViewData["pub"] = context.Publishers.ToList();
            TempData.Keep("userName");

Library/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CodeFirstContext;
using Library.Models;

namespace Library.Controllers
{
    public class DepartmentsController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();

        // GET: Departments
        public ActionResult Index()
        {
            TempData.Keep("userName");

            return View(context.Departments.ToList());
        }

        // GET: Departments/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Department department = context.Departments.Find(id);
        //    if (department == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(department);
        //}

        // GET: Departments/Create
        public ActionResult Create()
        {
            TempData.Keep("userName");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Department department)
        {
            if (ModelState.IsValid)
            {
                TempData.Keep("userName");

                context.Departments.Add(department);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = context.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            TempData.Keep("userName");

            return View(department);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Department department)
        {
            if (ModelState.IsValid)
            {
                TempData.Keep("userName");

                context.Entry(department).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = context.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            TempData.Keep("userName");

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TempData.Keep("userName");

            Department department = context.Departments.Find(id);
            context.Departments.Remove(department);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AllDepartment()
        {
            //User user = context.Users.FirstOrDefault(u => u.ID == userID);
            TempData.Keep("user");
            TempData.Keep("userName");

            return View(context.Departments.ToList());
        }
        public ActionResult AllBookInDept(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = context.Departments.Find(id);

            TempData.Keep("user");
            TempData.Keep("userName");

            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);

        }
        public ActionResult BookDetails(int? id)
        {
            TempData.Keep("user");
            TempData.Keep("userName");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = context.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        //public ActionResult Borrow(int? id)
        //{
        //    TempData.Keep("user");
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    if (TempData.ContainsKey("user"))
        //    {
        //        Book book = context.Books.Find(id);
        //        User user = TempData["user"] as User;
        //        Message message = new Message();
        //        message.User = user;
        //        message.Text = "Dear " + (message.User.Name).ToString() + " you borrow this book at " + (DateTime.Now.Date).ToString();
        //        if (book == null)
        //        {
        //            return HttpNotFound();
        //        }
        //        context.Messages.Add(message);
        //        context.SaveChanges();
        //    }
        //    return View();
        //}

    }
}

Library/Views/Books/AddNewBook.cshtml
@model Library.ViewModels.ViewModel

@{
    ViewBag.Title = "AddNewBook";
    Layout = "~/Views/Shared/_LayoutNew.cshtml";

    // SelectList depts = new SelectList(ViewBag.dept, "ID", "Name", Model.DepartmentID);

}

<h2>Add New Book</h2>


@using (Html.BeginForm("AddNewBook", "Books", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Book.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.ISBN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book.Yeare, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book.Yeare, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.Yeare, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Book.AuthorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book.AuthorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.AuthorName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Book.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Book.Image" required = "required" class="form-control">
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Book.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Book.File" required = "required" class="form-control">
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Book.File, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book.PublisherID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Book.PublisherID, Model.Publishers, "Select", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Book.PublisherID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Book.DepartmentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Book.DepartmentID, Model.Departments, "Select", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Book.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.UserID, new SelectList(ViewBag.usr, "ID", "Name"), "Select", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AllBook")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Library/Views/Books/Borrow.cshtml
@model Library.Models.Book

@{
    ViewBag.Title = "Borrow";
    Layout = "~/Views/Shared/_LayoutLogOut.cshtml";
}

<h2>Borrow</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publisher.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publisher.Name)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISBN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Yeare)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yeare)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImagePath)" height="250" width="300" />
        </dd>

    </dl>
</div>
<p>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrow" class="btn btn-default" /> |

            <a  href="~/Departments/AllBookInDept/@Model.DepartmentID">Back to Book List</a> | 
            
            @Html.ActionLink("Back to Department List", "AllDepartment", "Departments")  
            @*@Html.ActionLink("Back to Book List", "AllBookInDept","Departments", new { id = Model.Department.ID})*@ 

        </div>
    }
    @*@Html.ActionLink("Back to List", "Index")*@
</p>

Library/Views/Books/BorrowsBook.cshtml
@model IEnumerable<Library.Models.Book>

@{
    ViewBag.Title = "BorrowsBook";
    Layout = "~/Views/Shared/_LayoutLogOut.cshtml";
}

<h2>BorrowsBook</h2>
<script>
    function DeleteFun() {

        return confirm("Do you want to Delete it!");
    }
</script>
@if (ViewData.ContainsKey("Mess"))
{
    <div class="alert alert-info alert-dismissible fade show">
        @ViewData["Mess"]
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ISBN)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ISBN)
        </td>
        <td>
            <a href="~/Books/Remove/@item.ID" onclick="return DeleteFun()">Remove</a>

            @*@Html.ActionLink("Remove", "Remove", new { id = item.UserID, bookid = item.ID}, onclick = "return DeleteFun()")*@

            @*@Html.ActionLink("Delete", "Delete", new { id=item.ID })*@
        </td>
    </tr>
}

</table>

<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |*@
    @Html.ActionLink("Back to Department List", "AllDepartment", "Departments") |
</p>

Library/Views/Books/Edit.cshtml
@model Library.Models.Book

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutNew.cshtml";

}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Books", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Yeare, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Yeare, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Yeare, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AuthorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>
        <!---<div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.LabelFor(model => model.ImagePath, Model.ImagePath,new { htmlAttributes = new { @class = "form-control" } })
                <input type="file" name="Image" required = "required">
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>-->

        @*<div class="form-group">
                @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentID, "DepartmentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentID", new SelectList(ViewBag.dept, "ID", "Name"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublisherID, "PublisherID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PublisherID", new SelectList(ViewBag.pub, "ID", "Name"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PublisherID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AllBook")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}